name: Trigger Second Repo Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prints the current branch name
        run: echo "${GITHUB_BRANCH##*/}"
        env:
          GITHUB_BRANCH: ${{ github.ref_name }}

      - name: Trigger second repo workflow
        uses: V-Bhadauriya/SecondRepo/.github/workflows/2.yml@main
        with:
          ref: ${{ github.ref_name }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
